"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

_SCITEX_DEV_AVAILABLE = shutil.which("scitex-dev") is not None


@pytest.mark.skipif(
    not _SCITEX_DEV_AVAILABLE,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)
def test_ecosystem_audit_all_reports_clean_for_package():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    # `audit_all_for_package` raises AssertionError on non-zero exit;
    # returning None means the audit was clean.
    result = audit_all_for_package('scitex-events')
    # Assert
    assert result is None
